[project]
name = "flash-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "firebase-admin>=7.0.0",
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "requests>=2.32.4",
]
